### ISSUE TITLE
Browser detection not working

### ISSUE THREAD

**Issue by mvinoba** [tmc/nlm#3]
When I run `nlm auth` my cursor shows a loading icon and after 1 or 2 minutes it shows the following error:

```
nlm auth
nlm: launching browser to login... (profile:Default)  (set with NLM_BROWSER_PROFILE)
browser auth failed: auth data not found after timeout (URL: https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fnotebooklm.google.com%2F&followup=https%3A%2F%2Fnotebooklm.google.com%2F&ifkv=AeZLP9-ljg16-Me_MIpr-v_aQmCTCT5JS5gzdie(...)5DFGLj4F_fs1U1c&osid=1&passive=1209600&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S1831086377%3A1(...)1)
```

I'm running on a Windows environment with Chrome installed on the standard folders `Program Files\Google\Chrome\Application`.

**Comment by hawaaiianmiraclecreel** [comment]
i have multiple chrome profiles and im not sure which one its selecting because its not actually opening the browser. When I run nlm auth i get this 

"error nlm: launching browser to login... (profile: hawaaiianmiraclecreel)  (set with NLM_BROWSER_PROFILE)
browser auth failed: auth data not found after timeout " then the auth url from google, which i tried to paste into the browser to no avail

**Comment by mvinoba** [comment]
Yes. Devin's commit definitely didn't worked for me. I wonder if we can have a dockerized solution or something like that. Maybe manually exporting the the profile or cookies and then using a Docker container for nlm.
